### ISSUE TITLE
Seminário

### ISSUE THREAD

**Issue by nnsdtr** [nnsdtr/Flutter-vs-React#3]
# Seminário – Aplicações Distribuídas

## Resumo:
- **Grupo:** 5
- **Valor:** 20 pontos (12 doc. escrito + 8 apresentação)
- **Título:** FE Facebook/Google para SD.
- **Assuntos:**
   - React;
   - React native;
   - Flutter;
   - Exemplo prático.

## Instruções:

A) **Orientações gerais:**

> Os grupos de até 5 alunos deverão apresentar trabalhos de boa qualidade, tanto em termos de conteúdo como de forma, com referências bibliográficas adequadas e profundidade teórica condizente.

---

B) **Objetivos:**
> 1. Realizar uma pesquisa sobre o tema escolhido;
> 2. Elaborar uma apresentação em grupo sobre o tema, com _**profundidade adequada**_;
> 3. Apresentar um trabalho prático.

---

C) **Sobre a avaliação:**
> OBS: CÓPIAS DE TRABALHOS DE QUAISQUER FONTES RECEBERÃO NOTA 0 (ZERO).

> A avaliação do seminário _**será individual**_, baseada nos seguintes quesitos
> - Adequação, profundidade da pesquisa e aderência ao escopo;
> - Bibliografia utilizada (obs: NÃO UTILIZAR somente sites web ou artigos);
> - Apresentação (nota individual);
> - Exemplo apresentado (obrigatório);

**Comment by jptdias10** [comment]
Top
