### ISSUE TITLE
Parte escrita

### ISSUE THREAD

**Issue by nnsdtr** [nnsdtr/Flutter-vs-React#6]
##  **Sobre a parte escrita:**
> Data de entrega: último dia das apresentações (29/04, sexta-feira)

> Obs: O documento deverá seguir o Padrão PUC Minas de Normalização.

> A parte escrita deverá:
> 1. Ser constituída por um texto **_organizado e conciso_**;
> 2. Ser **_coerente com_** os slides apresentados
> 3. Estar em formato **_PDF_**
> 5. Possuir de **_10 a 15_** páginas no total;
> 6. Ser organizado em **_4 seções_**

| Seção | Título                     | Número de páginas |
|--------|:---------------------| ----------------------:|
| R1      | Capa                       | Não é contabilizada |
| S1      | Introdução              |                              1 |
| S2      | Referencial Teórico |                         5 a 7 |
| S3      |  Parte Prática          |                          2 a 3 |
| S4      |  Conclusão              |                               1 |
| R2      |  Referências            |                               1 |

**Comment by maycon26** [comment]
https://drive.google.com/file/d/1m_DIrc5ZwvpJG4TBlmPWd1__Jb8p_7yL/view?usp=sharing
